name: "✍️ Feature request 🔥"
description: "Suggest an idea for this project"
title: "Suggest a new feature"
labels:
    - feature
assignees: []

body:
    - type: textarea
      id: problem_description
      attributes:
          label: Problem Description
          description: Describe the problem your feature request is related to, if applicable.
          placeholder: Describe the problem...
      validations:
          required: true

    - type: textarea
      id: additional_context
      attributes:
          label: Additional Context
          description: Add any other context, screenshots, or code snippets related to the feature request.
          placeholder: Provide additional context.

    - type: textarea
      id: solution_description
      attributes:
          label: Solution Description
          description: Describe the solution you would like to see implemented.
          placeholder: Describe the solution...
      validations:
          required: true

    - type: textarea
      id: potential_implementation
      attributes:
          label: Potential Implementation
          description: Outline or steps on how this feature could be implemented, if known.
          placeholder: Provide potential implementation steps.
      validations:
          required: true

    - type: dropdown
      id: package
      attributes:
          label: Which @dynamic-filter/* package(s) are relevant/related to the feature request?
          multiple: true
          options:
              - core
              - components

    - type: dropdown
      id: importance
      attributes:
          label: Feature Importance
          description: Select how important you think this feature is.
          multiple: false
          options:
              - Must-have
              - Nice-to-have
              - Low priority
      validations:
          required: true
