name: "✍️ Feature request 🔥"
description: "Suggest an idea for this project"
title: ""
labels:
    - feature
assignees: []

body:
    - type: markdown
      attributes:
          value: |
              **Is your feature request related to a problem? Please describe.**  
              A clear and concise description of what the problem is. Ex. I'm frustrated when [...]

    - type: textarea
      id: problem_description
      attributes:
          label: Problem Description
          description: Describe the problem your feature request is related to, if applicable.
          placeholder: Describe the problem...

    - type: markdown
      attributes:
          value: |
              **Additional context**  
              Add any other context, screenshots, or code snippets about the feature request here.

    - type: textarea
      id: additional_context
      attributes:
          label: Additional Context
          description: Add any other context, screenshots, or code snippets related to the feature request.
          placeholder: Provide additional context.

    - type: markdown
      attributes:
          value: |
              **Describe the solution you'd like**  
              A clear and concise description of what you want to happen. Include any specific details, such as UI changes, data handling, or performance improvements.

    - type: textarea
      id: solution_description
      attributes:
          label: Solution Description
          description: Describe the solution you would like to see implemented.
          placeholder: Describe the solution...

    - type: markdown
      attributes:
          value: |
              **Potential implementation**  
              If possible, provide a brief outline or steps on how this feature could be implemented. This could include details on relevant files, libraries, or APIs that may need to be modified.

    - type: textarea
      id: potential_implementation
      attributes:
          label: Potential Implementation
          description: Outline or steps on how this feature could be implemented, if known.
          placeholder: Provide potential implementation steps.

    - type: markdown
      attributes:
          value: |
              **How important is this feature to you?**

    - type: checkboxes
      id: importance
      attributes:
          label: Feature Importance
          description: Select how important this feature is to you.
          options:
              - label: Must-have
              - label: Nice-to-have
              - label: Low priority
